import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });
import SessionWrapper from "@/components/SessionWrapper";

export const metadata = {
  title: "Maheshwari King",
  description: "Generated by King",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-[#000000] bg-[radial-gradient(#ffffff33_1px,#00091d_1px)] bg-[size:20px_20px]'>
          <SessionWrapper>
            <Navbar/>
            <div className="min-h-[84vh]">
              {children}
            </div>
            <Footer/>
          </SessionWrapper>
      </body>
    </html>
  );
}
